[package]
name = "CPlusPlusParser"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.24"
tree-sitter-cpp = "0.23.1"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
clap = { version = "4.5.20", features = ["derive"] }

[build-dependencies]
cc="*"